name = "rcuz"
author = "ElectroBear"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8be9198bcf7ee68bb15c60cd7451c015e833d0a9d31322f99c5d0a8d8ab904ea"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
