name = "rcuz"
author = "ElectroBear"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60434300e7bf940ac6f9676103d0b85c57fb34ed62d6701fe3ce2407e8b8963b"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
