name = "rcuz"
author = "ElectroBear"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d132824ce3a4a02e5e77e5c7c66dd240741b7bec42637d8e93fb0fe687e894b"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
