#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 17 20:29:03 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=11
shaderPack=BSL_v10.1.1.zip
enableShaders=false
