#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 09 16:16:05 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=11
shaderPack=Just Colored Lighting (0.9.9).zip
enableShaders=true
